"use client"

import { useCallback, useRef, useState, type ReactElement } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Loader2, Send, Trash2, HelpCircle, Languages, Sparkles } from "lucide-react"
import { cn } from "@/lib/utils"

type Role = "user" | "assistant"
type QuickCommandKind = "meaning" | "translate" | "naturalize"

const QUICK_MODAL: Record<
  QuickCommandKind,
  { title: string; subtitle: string; description: string; placeholder: string; cta: string; icon: typeof HelpCircle }
> = {
  meaning: {
    title: "뜻이 뭐야?",
    subtitle: "Word or phrase",
    description:
      "궁금한 영어 단어나 표현을 입력하면, 뜻과 뉘앙스를 한국어로 설명하고 짧은 예문을 들어줘요.",
    placeholder: "예: out of the blue, leverage, …",
    cta: "질문 보내기",
    icon: HelpCircle,
  },
  translate: {
    title: "번역해줘",
    subtitle: "English → Korean",
    description: "영어 문장이나 단락을 붙여넣으면 자연스러운 한국어로 옮겨줘요.",
    placeholder: "번역할 영어를 입력하거나 붙여넣기",
    cta: "번역 요청",
    icon: Languages,
  },
  naturalize: {
    title: "더 자연스럽게",
    subtitle: "Sound more native",
    description: "의미는 그대로 두고, 원어민이 말하듯 자연스럽게 다듬어줘요.",
    placeholder: "다듬을 영어 문장을 입력",
    cta: "다듬기 요청",
    icon: Sparkles,
  },
}

function buildQuickPrompt(kind: QuickCommandKind, value: string): string {
  const v = value.trim()
  switch (kind) {
    case "meaning":
      return `What does "${v}" mean? Explain meaning and nuance in Korean, and give one English example sentence with a short Korean gloss.`
    case "translate":
      return `Translate the following English into natural Korean. Keep names as appropriate. If it is a single word, also give the most common part of speech and one short example phrase in English with Korean gloss:\n\n${v}`
    case "naturalize":
      return `Rewrite the following so it sounds more natural in spoken English (like a native speaker). Keep the same meaning. First give the improved sentence only, then a short bullet list of what you changed and why:\n\n${v}`
  }
}

export interface TutorChatPanelProps {
  transcriptContext: string
  className?: string
}

const WELCOME =
  "Ask anything about English: grammar, natural phrasing, or your transcript on the left (optional context). Replies are generated by AI — verify critical facts yourself."

export function TutorChatPanel({ transcriptContext, className }: TutorChatPanelProps) {
  const [messages, setMessages] = useState<{ role: Role; content: string }[]>([])
  const [input, setInput] = useState("")
  const [sending, setSending] = useState(false)
  const [quickOpen, setQuickOpen] = useState(false)
  const [quickKind, setQuickKind] = useState<QuickCommandKind | null>(null)
  const [quickDraft, setQuickDraft] = useState("")
  const scrollRef = useRef<HTMLDivElement>(null)
  const bottomRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = useCallback(() => {
    const el = scrollRef.current
    if (el) {
      el.scrollTo({ top: el.scrollHeight, behavior: "smooth" })
      return
    }
    bottomRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [])

  const sendWithText = async (raw: string) => {
    const text = raw.trim()
    if (!text || sending) return
    const userMsg = { role: "user" as const, content: text }
    const thread = [...messages, userMsg]
    setSending(true)
    setInput("")
    setMessages(thread)
    requestAnimationFrame(() => scrollToBottom())

    try {
      const res = await fetch("/api/tutor-chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: thread, transcript_context: transcriptContext }),
      })
      const data = await res.json().catch(() => ({}))
      const reply =
        typeof data?.reply === "string" && data.reply.trim()
          ? data.reply.trim()
          : typeof data?.error === "string"
            ? `Sorry: ${data.error}`
            : "No reply from tutor."
      setMessages((prev) => [...prev, { role: "assistant", content: reply }])
    } catch {
      setMessages((prev) => [...prev, { role: "assistant", content: "Request failed. Try again in a moment." }])
    } finally {
      setSending(false)
      setTimeout(scrollToBottom, 100)
    }
  }

  const send = () => void sendWithText(input)

  const closeQuick = useCallback(() => {
    setQuickOpen(false)
    setQuickKind(null)
    setQuickDraft("")
  }, [])

  const openQuick = (kind: QuickCommandKind) => {
    if (sending) return
    setQuickKind(kind)
    setQuickDraft("")
    setQuickOpen(true)
  }

  const focusQuickField = () => {
    requestAnimationFrame(() => {
      document.getElementById("tutor-quick-field")?.focus()
    })
  }

  const confirmQuick = () => {
    if (!quickKind || sending) return
    const trimmed = quickDraft.trim()
    if (!trimmed) return
    const text = buildQuickPrompt(quickKind, trimmed)
    closeQuick()
    void sendWithText(text)
  }

  let quickDialogContent: ReactElement | null = null
  if (quickKind) {
    const meta = QUICK_MODAL[quickKind]
    const Icon = meta.icon
    const multiline = quickKind !== "meaning"
    quickDialogContent = (
      <DialogContent
        className="max-h-[min(92vh,40rem)] gap-0 overflow-hidden border-border/80 p-0 shadow-xl sm:max-w-lg"
        onOpenAutoFocus={(e) => {
          e.preventDefault()
          focusQuickField()
        }}
      >
        <div className="border-border/60 bg-muted/35 border-b px-5 pt-5 pb-4 sm:px-6">
          <DialogHeader className="text-left sm:pr-8">
            <div className="flex gap-3">
              <div className="bg-primary/12 text-primary flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-primary/15">
                <Icon className="h-5 w-5" aria-hidden />
              </div>
              <div className="min-w-0 flex-1 space-y-1">
                <DialogTitle className="text-balance text-base leading-snug font-semibold sm:text-lg">{meta.title}</DialogTitle>
                <p className="text-muted-foreground text-xs font-medium tracking-wide">{meta.subtitle}</p>
              </div>
            </div>
            <DialogDescription className="text-foreground/85 pt-3 text-left text-[13px] leading-relaxed">{meta.description}</DialogDescription>
          </DialogHeader>
        </div>

        <div className="px-5 py-4 sm:px-6">
          {multiline ? (
            <Textarea
              id="tutor-quick-field"
              value={quickDraft}
              onChange={(e) => setQuickDraft(e.target.value)}
              placeholder={meta.placeholder}
              rows={5}
              className="border-input min-h-32 resize-y rounded-xl border bg-card text-sm shadow-sm"
              onKeyDown={(e) => {
                if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
                  e.preventDefault()
                  confirmQuick()
                }
              }}
            />
          ) : (
            <form
              className="contents"
              onSubmit={(e) => {
                e.preventDefault()
                confirmQuick()
              }}
            >
              <Input
                id="tutor-quick-field"
                value={quickDraft}
                onChange={(e) => setQuickDraft(e.target.value)}
                placeholder={meta.placeholder}
                className="h-11 rounded-xl border bg-card px-3 text-sm shadow-sm"
                autoComplete="off"
              />
            </form>
          )}
          {multiline ? (
            <p className="text-muted-foreground mt-2 text-xs">⌘ 또는 Ctrl + Enter 로 바로 보내기</p>
          ) : (
            <p className="text-muted-foreground mt-2 text-xs">Enter 로 보내기</p>
          )}
        </div>

        <DialogFooter className="border-border/60 bg-muted/15 flex-col gap-3 border-t px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6">
          <p className="text-muted-foreground order-last text-left text-[11px] leading-snug sm:order-first sm:max-w-[55%]">
            {multiline ? "긴 문장·단락은 그대로 붙여넣어도 돼요." : "짧은 표현이면 한 줄로 입력하면 돼요."}
          </p>
          <div className="flex w-full gap-2 sm:w-auto sm:justify-end">
            <Button type="button" variant="outline" className="flex-1 sm:flex-none" onClick={closeQuick}>
              취소
            </Button>
            <Button type="button" className="flex-1 sm:flex-none" disabled={!quickDraft.trim() || sending} onClick={confirmQuick}>
              {meta.cta}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    )
  }

  return (
    <div className={cn("flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden", className)}>
      {!transcriptContext.trim() && (
        <p className="text-muted-foreground mx-3 mt-2 shrink-0 rounded-lg border border-dashed border-border bg-muted/50 px-2 py-1.5 text-[11px] leading-snug sm:mx-4">
          Tip: add transcript on the left for richer answers (optional).
        </p>
      )}

      {/* Single scroll surface — no nested scroll inside bubbles */}
      <div
        ref={scrollRef}
        className="min-h-0 flex-1 touch-pan-y overflow-y-auto overscroll-y-contain [-webkit-overflow-scrolling:touch] px-3 py-2 sm:px-4"
      >
        <div className="flex max-w-full flex-col gap-3 pb-2">
          <div className="text-muted-foreground bg-muted/80 mr-auto max-w-[min(100%,42rem)] rounded-2xl border border-border/60 px-3 py-2.5 text-xs leading-relaxed">
            {WELCOME}
          </div>
          {messages.map((m, i) => (
            <div
              key={`${i}-${m.role}-${m.content.length}`}
              className={cn(
                "max-w-[min(100%,42rem)] rounded-2xl px-3 py-2.5 text-sm leading-relaxed wrap-anywhere",
                m.role === "user"
                  ? "bg-primary text-primary-foreground ml-auto"
                  : "bg-muted text-foreground mr-auto border border-border/60"
              )}
            >
              <p className="whitespace-pre-wrap wrap-break-word">{m.content}</p>
            </div>
          ))}
          {sending && (
            <div className="text-muted-foreground flex items-center gap-2 text-xs">
              <Loader2 className="h-3.5 w-3.5 shrink-0 animate-spin" />
              Thinking…
            </div>
          )}
          <div ref={bottomRef} className="h-px w-full shrink-0" aria-hidden />
        </div>
      </div>

      {/* Thumb zone: quick commands + input + FAB send (bottom-right) */}
      <div className="border-border bg-background/95 shrink-0 border-t px-3 pt-2 pb-[max(0.65rem,env(safe-area-inset-bottom))] backdrop-blur supports-backdrop-filter:bg-background/90 sm:px-4">
        <p className="text-muted-foreground mb-1.5 text-[10px] font-medium tracking-wide uppercase">Quick prompts</p>
        <div className="mb-2 flex gap-1.5 overflow-x-auto pb-0.5 [-webkit-overflow-scrolling:touch]">
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="h-9 shrink-0 gap-1 rounded-full px-3 text-xs font-medium"
            disabled={sending}
            onClick={() => openQuick("meaning")}
          >
            <HelpCircle className="h-3.5 w-3.5" />
            뜻이 뭐야?
          </Button>
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="h-9 shrink-0 gap-1 rounded-full px-3 text-xs font-medium"
            disabled={sending}
            onClick={() => openQuick("translate")}
          >
            <Languages className="h-3.5 w-3.5" />
            번역해줘
          </Button>
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="h-9 shrink-0 gap-1 rounded-full px-3 text-xs font-medium"
            disabled={sending}
            onClick={() => openQuick("naturalize")}
          >
            <Sparkles className="h-3.5 w-3.5" />
            더 자연스럽게
          </Button>
        </div>

        <div className="relative pb-1">
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask in English or Korean…"
            rows={3}
            className="border-input min-h-21 w-full resize-none rounded-2xl border bg-card pr-14 pb-3 pl-3 pt-3 text-sm shadow-sm"
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault()
                void send()
              }
            }}
          />
          <Button
            type="button"
            size="icon"
            className="bg-primary text-primary-foreground hover:bg-primary/90 absolute bottom-3 right-2 z-10 h-11 w-11 rounded-full shadow-md"
            onClick={() => void send()}
            disabled={sending || !input.trim()}
            aria-label="Send message"
          >
            {sending ? <Loader2 className="h-5 w-5 animate-spin" /> : <Send className="h-5 w-5" />}
          </Button>
        </div>

        <div className="text-muted-foreground mt-1 flex items-center justify-between gap-2 text-[10px]">
          <span className="min-w-0 leading-snug">Enter = send · Shift+Enter = 줄바꿈</span>
          <Button type="button" variant="ghost" size="sm" className="text-muted-foreground h-8 shrink-0 gap-1 px-2 text-xs" onClick={() => setMessages([])}>
            <Trash2 className="h-3.5 w-3.5" />
            Clear
          </Button>
        </div>
      </div>

      <Dialog
        open={quickOpen}
        onOpenChange={(open) => {
          if (!open) closeQuick()
        }}
      >
        {quickDialogContent}
      </Dialog>
    </div>
  )
}
