"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Loader2, Send, Trash2, HelpCircle, Languages, Sparkles, BookmarkPlus, X, Plus } from "lucide-react"

import { cn } from "@/lib/utils"
import type { VocabularyItem, TutorChatMessage } from "@/lib/types"

type Role = "user" | "assistant"
type QuickKind = "meaning" | "translate" | "naturalize"

type AddVocabPayload = {
  word: string
  type: VocabularyItem["type"]
  definition?: string
  context?: string
}

const QUICK_TABS: {
  kind: QuickKind
  label: string
  icon: typeof HelpCircle
  placeholder: string
  hint: string
  multiline: boolean
  buildPrompt: (v: string) => string
}[] = [
  {
    kind: "meaning",
    label: "뜻이 뭐야?",
    icon: HelpCircle,
    placeholder: "예: out of the blue, leverage, …",
    hint: "뜻·뉘앙스를 한국어로 설명하고 예문을 들어줘요.",
    multiline: false,
    buildPrompt: (v) =>
      `What does "${v}" mean? Explain meaning and nuance in Korean, and give one English example sentence with a short Korean gloss.`,
  },
  {
    kind: "translate",
    label: "번역해줘",
    icon: Languages,
    placeholder: "번역할 영어를 입력하거나 붙여넣기",
    hint: "영어 문장·단락을 자연스러운 한국어로 옮겨줘요.",
    multiline: true,
    buildPrompt: (v) =>
      `Translate the following English into natural Korean. Keep names as appropriate. If it is a single word, also give the most common part of speech and one short example phrase in English with Korean gloss:\n\n${v}`,
  },
  {
    kind: "naturalize",
    label: "더 자연스럽게",
    icon: Sparkles,
    placeholder: "다듬을 영어 문장을 입력",
    hint: "원어민처럼 자연스럽게 다듬고, 변경 이유를 설명해줘요.",
    multiline: true,
    buildPrompt: (v) =>
      `Rewrite the following so it sounds more natural in spoken English (like a native speaker). Keep the same meaning. First give the improved sentence only, then a short bullet list of what you changed and why:\n\n${v}`,
  },
]

export interface TutorChatPanelProps {
  transcriptContext: string
  className?: string
  onAddVocabularyItem?: (payload: AddVocabPayload) => void
  onSaveSession?: (messages: TutorChatMessage[]) => void
}

const WELCOME =
  "Ask anything about English: grammar, natural phrasing, or your transcript on the left (optional context). Replies are generated by AI — verify critical facts yourself."

type AddFormState = {
  msgIdx: number
  text: string
  type: VocabularyItem["type"]
}

export function TutorChatPanel({ transcriptContext, className, onAddVocabularyItem, onSaveSession }: TutorChatPanelProps) {
  const [messages, setMessages] = useState<TutorChatMessage[]>([])
  const [sending, setSending] = useState(false)

  const messagesRef = useRef(messages)
  useEffect(() => { messagesRef.current = messages }, [messages])

  // Auto-save on unmount if there are messages
  useEffect(() => {
    return () => {
      if (messagesRef.current.length > 0) {
        onSaveSession?.(messagesRef.current)
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Quick prompt tab state
  const [activeQuick, setActiveQuick] = useState<QuickKind | null>(null)
  const [quickDraft, setQuickDraft] = useState("")

  // Vocab add form per message
  const [addForm, setAddForm] = useState<AddFormState | null>(null)

  const scrollRef = useRef<HTMLDivElement>(null)
  const bottomRef = useRef<HTMLDivElement>(null)
  const quickInputRef = useRef<HTMLInputElement & HTMLTextAreaElement>(null)

  const scrollToBottom = useCallback(() => {
    const el = scrollRef.current
    if (el) {
      el.scrollTo({ top: el.scrollHeight, behavior: "smooth" })
      return
    }
    bottomRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [])

  const sendWithText = async (raw: string) => {
    const text = raw.trim()
    if (!text || sending) return
    const userMsg = { role: "user" as const, content: text }
    const thread = [...messages, userMsg]
    setSending(true)
    setMessages(thread)
    requestAnimationFrame(() => scrollToBottom())

    try {
      const res = await fetch("/api/tutor-chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: thread, transcript_context: transcriptContext }),
      })
      const data = await res.json().catch(() => ({}))
      const reply =
        typeof data?.reply === "string" && data.reply.trim()
          ? data.reply.trim()
          : typeof data?.error === "string"
            ? `Sorry: ${data.error}`
            : "No reply from tutor."
      setMessages((prev) => [...prev, { role: "assistant", content: reply }])
    } catch {
      setMessages((prev) => [...prev, { role: "assistant", content: "Request failed. Try again in a moment." }])
    } finally {
      setSending(false)
      setTimeout(scrollToBottom, 100)
    }
  }

  const selectQuickTab = (kind: QuickKind) => {
    if (sending) return
    if (activeQuick === kind) {
      setActiveQuick(null)
      setQuickDraft("")
    } else {
      setActiveQuick(kind)
      setQuickDraft("")
      requestAnimationFrame(() => quickInputRef.current?.focus())
    }
  }

  const submitQuick = () => {
    if (!activeQuick || sending) return
    const trimmed = quickDraft.trim()
    if (!trimmed) return
    const tab = QUICK_TABS.find((t) => t.kind === activeQuick)!
    const prompt = tab.buildPrompt(trimmed)
    setActiveQuick(null)
    setQuickDraft("")
    void sendWithText(prompt)
  }

  const openAddForm = (msgIdx: number, content: string) => {
    const firstLine = content.split("\n")[0].trim().slice(0, 120)
    setAddForm({ msgIdx, text: firstLine, type: "expression" })
  }

  const submitAddForm = () => {
    if (!addForm || !onAddVocabularyItem) return
    const word = addForm.text.trim()
    if (!word) return
    onAddVocabularyItem({ word, type: addForm.type })
    setAddForm(null)
  }

  const activeTab = activeQuick ? QUICK_TABS.find((t) => t.kind === activeQuick)! : null

  return (
    <div className={cn("flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden", className)}>
      {!transcriptContext.trim() && (
        <p className="text-muted-foreground mx-3 mt-2 shrink-0 rounded-lg border border-dashed border-border bg-muted/50 px-2 py-1.5 text-[11px] leading-snug sm:mx-4">
          Tip: add transcript on the left for richer answers (optional).
        </p>
      )}

      {/* Message list */}
      <div
        ref={scrollRef}
        className="min-h-0 flex-1 touch-pan-y overflow-y-auto overscroll-y-contain [-webkit-overflow-scrolling:touch] px-3 py-2 sm:px-4"
      >
        <div className="flex max-w-full flex-col gap-3 pb-2">
          <div className="text-muted-foreground bg-muted/80 mr-auto max-w-[min(100%,42rem)] rounded-2xl border border-border/60 px-3 py-2.5 text-xs leading-relaxed">
            {WELCOME}
          </div>

          {messages.map((m, i) => (
            <div key={`${i}-${m.role}-${m.content.length}`} className="flex flex-col gap-1">
              <div
                className={cn(
                  "max-w-[min(100%,42rem)] rounded-2xl px-3 py-2.5 text-sm leading-relaxed wrap-anywhere",
                  m.role === "user"
                    ? "bg-primary text-primary-foreground ml-auto"
                    : "bg-muted text-foreground mr-auto border border-border/60"
                )}
              >
                <p className="whitespace-pre-wrap wrap-break-word">{m.content}</p>
              </div>

              {/* Add vocab action — only on assistant messages */}
              {m.role === "assistant" && onAddVocabularyItem && (
                <div className="mr-auto flex items-center gap-1 pl-1">
                  {addForm?.msgIdx === i ? (
                    <div className="flex items-start gap-2 rounded-xl border border-border/60 bg-card px-3 py-2.5 shadow-sm max-w-sm w-full">
                      <div className="flex flex-1 flex-col gap-2 min-w-0">
                        <Input
                          value={addForm.text}
                          onChange={(e) => setAddForm({ ...addForm, text: e.target.value })}
                          placeholder="단어 또는 표현"
                          className="h-8 rounded-lg text-xs"
                          onKeyDown={(e) => {
                            if (e.key === "Enter") { e.preventDefault(); submitAddForm() }
                            if (e.key === "Escape") setAddForm(null)
                          }}
                          autoFocus
                        />
                        <div className="flex items-center gap-1.5 flex-wrap">
                          {(["word", "idiom", "slang", "phrasal_verb", "expression"] as VocabularyItem["type"][]).map((t) => (
                            <button
                              key={t}
                              type="button"
                              onClick={() => setAddForm({ ...addForm, type: t })}
                              className={cn(
                                "rounded-full px-2 py-0.5 text-[10px] font-medium border transition-colors",
                                addForm.type === t
                                  ? "bg-primary text-primary-foreground border-primary"
                                  : "bg-muted text-muted-foreground border-border hover:border-primary/50"
                              )}
                            >
                              {t}
                            </button>
                          ))}
                        </div>
                      </div>
                      <div className="flex shrink-0 flex-col gap-1">
                        <Button size="icon" className="h-7 w-7 rounded-lg" onClick={submitAddForm} disabled={!addForm.text.trim()}>
                          <Plus className="h-3.5 w-3.5" />
                        </Button>
                        <Button size="icon" variant="ghost" className="h-7 w-7 rounded-lg" onClick={() => setAddForm(null)}>
                          <X className="h-3.5 w-3.5" />
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <button
                      type="button"
                      onClick={() => openAddForm(i, m.content)}
                      className="flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] text-muted-foreground hover:text-foreground hover:bg-muted transition-colors border border-transparent hover:border-border/60"
                    >
                      <BookmarkPlus className="h-3 w-3" />
                      단어/표현 추가
                    </button>
                  )}
                </div>
              )}
            </div>
          ))}

          {sending && (
            <div className="text-muted-foreground flex items-center gap-2 text-xs">
              <Loader2 className="h-3.5 w-3.5 shrink-0 animate-spin" />
              Thinking…
            </div>
          )}
          <div ref={bottomRef} className="h-px w-full shrink-0" aria-hidden />
        </div>
      </div>

      {/* Bottom input zone */}
      <div className="border-border bg-background/95 shrink-0 border-t px-3 pt-2.5 pb-[max(0.65rem,env(safe-area-inset-bottom))] backdrop-blur supports-backdrop-filter:bg-background/90 sm:px-4">

        {/* Quick prompt tab buttons */}
        <div className="mb-2 flex gap-1.5">
          {QUICK_TABS.map(({ kind, label, icon: Icon }) => (
            <button
              key={kind}
              type="button"
              disabled={sending}
              onClick={() => selectQuickTab(kind)}
              className={cn(
                "flex h-8 items-center gap-1.5 rounded-full border px-3 text-xs font-medium transition-all",
                activeQuick === kind
                  ? "border-primary bg-primary text-primary-foreground shadow-sm"
                  : "border-border bg-muted/50 text-muted-foreground hover:border-primary/40 hover:text-foreground"
              )}
            >
              <Icon className="h-3.5 w-3.5 shrink-0" />
              {label}
            </button>
          ))}
        </div>

        {/* Inline quick prompt form */}
        {activeTab && (
          <div className="mb-2 rounded-xl border border-border/70 bg-muted/40 px-3 py-2.5">
            <p className="text-muted-foreground mb-2 text-[11px] leading-snug">{activeTab.hint}</p>
            <div className="flex gap-2">
              {activeTab.multiline ? (
                <Textarea
                  ref={quickInputRef as React.RefObject<HTMLTextAreaElement>}
                  value={quickDraft}
                  onChange={(e) => setQuickDraft(e.target.value)}
                  placeholder={activeTab.placeholder}
                  rows={2}
                  className="min-h-0 flex-1 resize-none rounded-lg border-input bg-card text-sm"
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) { e.preventDefault(); submitQuick() }
                    if (e.key === "Escape") { setActiveQuick(null); setQuickDraft("") }
                  }}
                />
              ) : (
                <Input
                  ref={quickInputRef as React.RefObject<HTMLInputElement>}
                  value={quickDraft}
                  onChange={(e) => setQuickDraft(e.target.value)}
                  placeholder={activeTab.placeholder}
                  className="flex-1 rounded-lg text-sm"
                  onKeyDown={(e) => {
                    if (e.key === "Enter") { e.preventDefault(); submitQuick() }
                    if (e.key === "Escape") { setActiveQuick(null); setQuickDraft("") }
                  }}
                />
              )}
              <Button
                type="button"
                size="icon"
                className="h-9 w-9 shrink-0 rounded-lg"
                disabled={!quickDraft.trim() || sending}
                onClick={submitQuick}
              >
                {sending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
              </Button>
            </div>
            {activeTab.multiline && (
              <p className="text-muted-foreground mt-1 text-[10px]">⌘ Ctrl+Enter로 보내기 · Esc로 닫기</p>
            )}
          </div>
        )}

        <div className="mt-1 flex justify-end">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="text-muted-foreground h-7 shrink-0 gap-1 px-2 text-xs"
            onClick={() => {
              if (messages.length > 0) onSaveSession?.(messages)
              setMessages([])
            }}
          >
            <Trash2 className="h-3.5 w-3.5" />
            Clear
          </Button>
        </div>
      </div>
    </div>
  )
}
